### PR TITLE
Add new CI workflow to run G tests in PRs

### PR DESCRIPTION
**Pull request by aepete**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This change adds a new "CI" workflow configured to run measurementlink-labview G tests in PRs.

### Why should this Pull Request be merged?

Although there are limitations in what can be tested by this workflow at this time, exercising these tests at PR-time should reduce the risk of introducing breaking changes.  The availability of this workflow might also encourage addition of more automated testing as new changes come in.  And the workflow itself serves as a starting point for potentially more automation / dev efficiency (... automated build of VI packages, automated g diff screenshots in PRs, etc.)

### What testing has been done?

The PR itself demonstrates its value:
- Notice the "Checks" tab now indicates the "Run G Tests" workflow has been run upon having created / updated this PR.
- Created / updated the PR while having one or more tests in broken conditions; the workflow ran and failed and reported pertinent information about the respective failures in the logs.  (Notice the red x next to some of the intermediate commits.)
- Corrected the tests in the above-mentioned broken conditions, after which the workflow ran and succeeded, having succeeded on 9 of 9 specified G tests.  (Notice the green checkmarks and informative content in the logs.)

### Additional Design Notes
The G tests are invoked via the following flow:
PR update -> "CI" workflow -> "Run G Tests" workflow -> `run_tests.py` -> `run_tests.vi`

I've also included a rudimentary batch script, which can be used to mimic the test flow, locally, for developers on Windows:
`run_tests.bat` -> `run_tests.py` -> `run_tests.vi`

- `run_tests.py` invokes `run_tests.vi` through the LabVIEWCLI, which also serves as the means for results to be returned to the python script.
- `run_tests.vi` is a simple test-runner VI that iterates through tests specified in a provided list (`Tests.lst`), invokes them, and collates results.

Note that the overall flow roughly mimics elements of grpc-labview's CI / [build_release_artifacts.yml](https://github.com/ni/grpc-labview/blob/master/.github/workflows/build_release_artifacts.yml): "Run CI Tests" workflow.

At this time, this runner has limitations, in terms of scope & capabilities.  And perhaps it's best that it remains that way...
- Tests are run on a machine that's currently hand-provisioned with a shipping MeasurementLink 1.0 stack, plus LabVIEW 2020-64 SP1 with grpc-labview 1.0.0.1.  
  - Depending on how usage of this workflow evolves, we _could_ pursue testing against latest / daily stacks at some point...  Or updated to the latest ~monthly "drop" stack, as applicable...  
    - However, daily stack testing seems better suited with a wholly different approach, such as a dashboard events running against software installed via mobilize.
- The workflows do not (yet?) build measurementlink-labview packages or install them into the LV environment for test; therefore, it's implied that the tests exercised by this workflow _must be executed against the respective G source_.
  - This explains why the pre-existing Template test has been omitted from `Tests.lst` at this time, since its respective source depends on pre-installation of the MeasurementLink Service VIP.
  - We might pursue means of testing against installed MeasurementLink .vipbs as part of this workflow or some new workflow (or different runner machine?) in some future update.

### CODE REVIEW

**Comment by aepete** [comment]
`run_tests.vi` Front panel:
image

`run_tests.vi` Front panel after a successful local run:
image

`run_tests.vi` complete diagram:
image
- Hidden outer `Error` case (for condition: error occurred prior to iterating through tests) simply pushes an error summary to both the `stdout | stderr` and `Full Report` tunnels.
- Hidden inner `True` case (for condition: all tests passed) refrains from appending any failure information from the test result summary string.
- Innermost `Error` case (for condition: execution of test returned some error) lists the error code next to the test result and combines an error summary with the test's `result`, as shown below.
- Innermost `False` case (for condition: non-empty error/details string) appends the test result summary line with the pertinent error / result detail information, as shown below.
image

**Comment by dixonjoel** [comment]
@aepete How does the machine provisioning work? The only related thing I see is 'self-hosted' in the 'run_g_tests.yml'. Where's the machine and how did you set it up? Maybe we should add instructions to CONTRIBUTING.md.

**Comment by aepete** [comment]
> @aepete How does the machine provisioning work? The only related thing I see is 'self-hosted' in the 'run_g_tests.yml'. Where's the machine and how did you set it up? Maybe we should add instructions to CONTRIBUTING.md.

@dixonjoel good question.  I can add instructions to `CONTRIBUTING.md`.
- I've used my old test machine `spawningpool`, which physically sits in the MeasurementLink area and is configured with DAQ Imaging.
- I followed github's instructions for setting up `spawningpool` as a [new self-hosted runner](https://github.com/ni/measurementlink-labview/settings/actions/runners/new).
  - Self-hosting seemed to be the simplest option for getting LV installed & configured as desired.
  - You can see `spawningpool` shows up in this repo's [runners list](https://github.com/ni/measurementlink-labview/settings/actions/runners), and it includes a `self-hosted` tag.
- I installed the core MeasurementLink 1.0 + LV stack to `spawningpool`: InstrumentStudio, TestStand, MeasurementLink, LV2020-64 sp1 (plus grpc-labview 1.0.0.1 vips).
- Additional manual setup on spawningpool:
  - Enabled Long Paths in windows registry. (The github checkout action uses deep directory structure, which was exceedingly long when combined with path lengths for some of our examples & our client/server G code.)
  - Enabled VI Server in LabVIEW. (Prerequisite for usage of LabVIEWCLI to invoke LV from python.)
  - Configured github action-runner script, MeasurementLink Discovery Service, and LabVIEW as startup apps.  (This should ensure that everything needed by the runner and the tests should be ready to go whenever the machine gets rebooted.)

**Review by dixonjoel — CHANGES_REQUESTED** [review]
Waiting for the CONTRIBUTING.md updates.

**Pull request merged**
