### PR TITLE
examples: Update examples' TestStand sequence file to use the Update pin map step

### PR DESCRIPTION
**Pull request by Jayaseelan-James**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).
- [ ]  Automatically post PR comments with images for G code changes?

### What does this Pull Request accomplish?
- Updates all the examples TestStand sequence file to use the Update pin map step.
- Removes the PinMapPath variable under the MeasurementLink FileGlobals container.
- Removes the Unregister pin map step from the clean-up section.
- Remove the unused `Update Pin Map.vi` from the example projects.
[#2586986](https://dev.azure.com/ni/DevCentral/_workitems/edit/2586986)
[#2586988](https://dev.azure.com/ni/DevCentral/_workitems/edit/2586988)

### Why should this Pull Request be merged?
Keeps all the example projects and sequence files in sync with the new Update pin map step.

### What testing has been done?
Verified the NI-DCPowerSourceDCVoltage, NI-DMM, NI-FGEN, NI-SCOPE Measurement sequence execution using the simulated instrument.

Environment: 
Verified the Sequence file execution by copying and pasting:

- The corresponding TestStand version's INI file and the [MeasurementLinkString.ini](https://dev.azure.com/ni/DevCentral/_git/ASW?path=/Source/MeasurementServices/TestStandCustomStep/Components/Language/English/MeasurementLinkStrings.ini) from the latest main. 
- The TestStand202XMeasurementClient DLLs from the latest main.

Note: You could get the latest MeasurementLink installer from argo (please make sure to have installed both MeasurementLink 2024 Q1 and MeasurementLink Support for TestStand 202X 2024 Q1).

**_To-Do_**: Must verify the Keysight 34401A DMM, NI-Digital SPI and VISA Measurement sequences with the hardware.

### CODE REVIEW

**Comment by Jayaseelan-James** [comment]
@bkeryan Please help validate the Keysight 34401A DMM Measurement, NI-Digital SPI Measurement and VISA Measurement Measurement sequences with the hardware.

**Review by jasonmreding — APPROVED** [review]

**Comment by bkeryan** [comment]
> @bkeryan Please help validate the Keysight 34401A DMM measurement, NI-Digital SPI and VISA measurement sequences with the hardware.

I'm getting the latest bits installed so I can test this.

I don't have NI-Digital hardware. It supports simulation with nisimdev just like NI-FGEN does.

**Comment by bkeryan** [comment]
The 34401 TestStand sequence works.

**Review by pbirkhol-ni — CHANGES_REQUESTED** [review]
Can you hold off on submitting this until I investigate some build failures that @bkeryan was seeing? I will get to it in a few hours.

**Comment by pbirkhol-ni** [comment]
> Can you hold off on submitting this until I investigate some build failures that @bkeryan was seeing? I will get to it in a few hours.

I was able to build this on my machine. So I think it is okay to submit.

**Review by pbirkhol-ni — APPROVED** [review]

**Pull request merged**
