### PR TITLE
examples: update teststand sequence files to be in sync with latest measurement updates

### PR DESCRIPTION
**Pull request by jayaseelan-james**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md). _(Required)_
- [ ]  Automatically post PR comments with images for G code changes? _(Recommended for small changes)_

### What does this Pull Request accomplish?
Updates the TestStand sequence files that go with the examples to reflect the latest measurement updates.

### Why should this Pull Request be merged?
It helps in keeping the TestStand sequence files up-to-date with their example measurements.

You can see similar changes for the measurementlink-python in this PR: https://github.com/ni/measurementlink-python/pull/704

### Sample snapshots of the changes:

Before:
image

Now:
image

### What testing has been done?
NA. Simple type changes.

### CODE REVIEW

**Comment by jasonmreding** [comment]
Since these are all binary files with no diffs, can you give a little more information on exactly what was changed in the sequence files?

**Comment by jayaseelan-james** [comment]
> Since these are all binary files with no diffs, can you give a little more information on exactly what was changed in the sequence files?

Sure. I've attached a couple of images below showcasing the changes. Primarily, it updates the pin type to IOResource and in the NI-SCOPE measurement, it additionally updates the names of pin and trigger source parameter.

Before:
image

Now:
image

Before:
image

Now:
image

**Comment by dixonjoel** [comment]
> > Since these are all binary files with no diffs, can you give a little more information on exactly what was changed in the sequence files?
> 
> Sure. I've attached a couple of images below showcasing the changes. Primarily, it updates the pin type to IOResource and in the NI-SCOPE measurement, it additionally updates the names of pin and trigger source parameter.
> 
> Before: image
> 
> Now: image
> 
> Before: image
> 
> Now: image

Did you have to make any changes to the sequence or just open and save them? Don't these string changes just happen when you open the sequence with a new version of MeasurementLink installed that has the new I/O resource data type names?

**Comment by jayaseelan-james** [comment]
> Did you have to make any changes to the sequence or just open and save them? Don't these string changes just happen when you open the sequence with a new version of MeasurementLink installed that has the new I/O resource data type names?

I had to click the Refresh button in the measurement step settings once to get these changes saved. Other than that, I didn't touch the sequence file.

**Review by dixonjoel — APPROVED** [review]

**Pull request merged**
