### PR TITLE
Remove old dependencies

### PR DESCRIPTION
**Pull request by gpachecoNI**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-labview/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

This PR eliminates old dependencies to files that got their name changed. 

### Why should this Pull Request be merged?

Fixes a dependency issue when trying to build MeasurmentLink Service.vipb

### What testing has been done?

Build MeasurmentLink Service.vipb from a manual folder download.

### CODE REVIEW

**Comment by dixonjoel** [comment]
I'm still seeing these on disk. Which PR did they supposedly get deleted in? E.g.
https://github.com/ni/measurementlink-labview/blob/main/Source/Runtime/MeasurementLink%20Measurement%20Server%20Internal/RPC%20Messages/ni_measurementlink_measurement_v1_ConfigurationParameter_AnnotationsEntry.ctl

**Comment by dixonjoel** [comment]
Also, I built MeasurementLink Service.vipb successfully just now.

**Comment by pbirkhol-ni** [comment]
> I'm still seeing these on disk. Which PR did they supposedly get deleted in? E.g. https://github.com/ni/measurementlink-labview/blob/main/Source/Runtime/MeasurementLink%20Measurement%20Server%20Internal/RPC%20Messages/ni_measurementlink_measurement_v1_ConfigurationParameter_AnnotationsEntry.ctl

These libraries are the generated output of `grpc-labview` for `measurement_service.proto`, which hasn't changed since adding V2 support months ago. So I don't think this change is necessary.

**Comment by gpachecoNI** [comment]
> I'm still seeing these on disk. Which PR did they supposedly get deleted in? E.g. https://github.com/ni/measurementlink-labview/blob/main/Source/Runtime/MeasurementLink%20Measurement%20Server%20Internal/RPC%20Messages/ni_measurementlink_measurement_v1_ConfigurationParameter_AnnotationsEntry.ctl



> I'm still seeing these on disk. Which PR did they supposedly get deleted in? E.g. https://github.com/ni/measurementlink-labview/blob/main/Source/Runtime/MeasurementLink%20Measurement%20Server%20Internal/RPC%20Messages/ni_measurementlink_measurement_v1_ConfigurationParameter_AnnotationsEntry.ctl

This is the PR where it got deleted. 
https://github.com/ni/measurementlink-labview/pull/215/files#diff-fb0edc361b57a61843f376721801c3104db3a963b944831cfd59c8291cf97e8f

**Comment by gpachecoNI** [comment]
> Also, I built MeasurementLink Service.vipb successfully just now.

I am not sure how it works.. If you do git pull and build it works but if you download the zipcode and try to build it doesn't.  
This is the bug nad how the error looks.

**Comment by gpachecoNI** [comment]
> > I'm still seeing these on disk. Which PR did they supposedly get deleted in? E.g. https://github.com/ni/measurementlink-labview/blob/main/Source/Runtime/MeasurementLink%20Measurement%20Server%20Internal/RPC%20Messages/ni_measurementlink_measurement_v1_ConfigurationParameter_AnnotationsEntry.ctl
> 
> These libraries are the generated output of `grpc-labview` for `measurement_service.proto`, which hasn't changed since adding V2 support months ago. So I don't think this change is necessary.

How do we regenerate them then?

**Comment by gpachecoNI** [comment]
The files of the issue are any reference.. After opening the MeasurementLink Measurement Server.lvlib and closing even without saving is impossible to reproduce.

**Pull request closed without merging**
